name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Force Xcode 12
      run: xcodebuild -project 'GitHubAction.xcodeproj' -scheme 'GitHubAction' -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest' 
    - name: GitHubAction
      run: xcodebuild -project 'GitHubAction.xcodeproj' -scheme 'GitHubAction' -destination 'generic/platform=iOS' --configuration "Ad Hoc" archive
